version: '3.4'

networks:
  mongotest:

services:
  mongodbdocker:
    image: ${DOCKER_REGISTRY-}mongodbdocker
    build:
      context: .
      dockerfile: ./MongoDbDocker/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://mongo:27017/
      - DatabaseSettings__Database=People
      - DatabaseSettings__CollectionName=Person
    networks:
      - mongotest
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
     - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongotest

volumes:
  mongodata:
    driver: local